// Generated by CoffeeScript 1.3.3
(function() {
  var utils;

  utils = {
    qa: function(selector, scope) {
      var nodes;
      nodes = (scope || document).querySelector(selector);
      return Array.prototype.slice.call(nodes);
    }
  };

}).call(this);
